[package]
name = "origin-trial-token"
version = "0.1.0"
edition = "2021"
authors = [
  "Emilio Cobos Álvarez <emilio@crisal.io>",
]
description = "An implementation of the Chrome Origin Trial token format"
repository = "https://github.com/mozilla/origin-trial-token"
license = "MPL-2.0"

[lib]
path = "lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
base64 = "0.13"
